import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import Result from '../components/Card'
import Link from "next/link";
import Login from './login';

export default function Home() {
  const [data, setData] = useState([])
  const router = useRouter()
  const [nama,setNama] = useState(0)

  useEffect(() => {
    setNama(localStorage.getItem("user_id"))
    
    fetch(`${process.env.NEXT_PUBLIC_API_URL}show/`)
      .then(res => res.json())
      .then(res => setData(res.shows))
  }, [])

  const signOut = async (event) => {
    localStorage.removeItem("user_id")
    event.preventDefault()
    await fetch(`${process.env.NEXT_PUBLIC_API_URL}logout/`, {
        method: 'POST',
      })
      .then(res => res.json())
      .then(router.push("/login"))
  } 
  useEffect(() => {
    if (localStorage.getItem("user_id")=== null) {
      router.push("/login");
    }
  }, [ router]);


  return (
    <>
      <Head>
        <title>TV SHOW INFO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello, {nama}</h1>
      <button onClick={signOut} className="transition-all duration-250 hover:text-red-500">
        Sign Out
      </button>
      <Link href="/" className="transition-all duration-250 hover:text-red-500">
          <p>Home</p>
        </Link>
        <Link href="/watchlist" className="transition-all duration-250 hover:text-red-500">
          <p>Watch List</p>
        </Link>
      <div className="w-full min-h-screen h-full flex flex-col items-center py-4">
        <h1 className="text-2xl font-bold">TV SHOW INFORMATION</h1>
        <div className="h-full w-full px-16 my-8 space-y-4">
          <div className="flex justify-between items-center w-full">
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 2xl:grid-cols-6 gap-8">
            {data.map((item, index) => {
              return (
                <Result id={item?.id} key={index} imageUrl={item?.poster_url} title={item?.title} genre={item?.genre} />
              )
            })}
          </div>
        </div>
      </div>
    </>
  )
}